const WordsActionTypes = {
    ADD_WORD: "ADD_WORD",
    SELECT_VALUE: "SELECT_VALUE",
    RESELECT_VALUE: "RESELECT_VALUE",
    SELECT_VALUE_ITEM: "SELECT_VALUE_ITEM",
    EDIT_NEW_CHANGES: "EDIT_NEW_CHANGES",

    //Saga
    CHECK_ELEMENT_PARAMETERS: "CHECK_ELEMENT_PARAMETERS",
    CHECK_LETTERS_ARRAY:"CHECK_LETTERS_ARRAY"
}

export default WordsActionTypes;
